### PR TITLE
Cleaning up

### PR DESCRIPTION
**Pull request by stephenc87**
Removing some junk, improving some comments, adding a little style and removing the sleep ZZZzzz...

### CODE REVIEW

**Comment by Admin9705** [comment]
looks good, i'll have to check on the weekend. if good, merge changes and then push to site. thanks for helping!

**Comment by stephenc87** [comment]
Some of the comments look rather unnecessary, @MrDoobPG seems to think otherwise, should we begin asking the user questions here

**Comment by Admin9705** [comment]
its because when the installer starts, it does ansible and etc for install; preventing problems for some people, but ya we can look into it.

**Comment by robertbaker** [comment]
What exactly is your concern here @stephenc87 ??

So you rather rely on users to install dependencies??

How is making sure your system having the latest updates and the packages needed a bad thing??

**Comment by stephenc87** [comment]
I am not sure what you mean by reselling PlexGuide services? I can't imagine a business model that it would fit in to for that to work.....
The project has some good suggestions and I provide my server to local users for free, part of a hobby of mine, I don't make any money from this whatsoever

I don't have to be writing any of this either, I could be doing something else with my time, but I have found myself here and I may as well share what I can

As far as new users are concerned, that's what your documentation is for, if you want a user to install xyz package or access a said repository, you mention that to the user, if they can run an install script they can type "sudo apt-get xyz" or "dpkg --install xyz.deb" themselves, if you want to make this process automatic, build a .deb or .rpm file, if you are worried about dependencies being out of date then set up your own repository with tested dependencies, I really don't mind helping out with this

**Comment by stephenc87** [comment]
@robertbaker There is a safer way to do all this, and no, I am not trying to make money of this project, what a weird thing to say???
My concern is that after some time, changes like this may result in a tainted install, why don't we use a package manager for these tasks if we are worried about confusing users, it would make a lot more sense and make updates easier to roll out

**Pull request closed without merging**
